#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application name
application=`getApplication`

wmake libso setEndPointTwisting

createMultipleCircularBeamMesh > log.createMultipleCircularBeamMesh
transformPoints -rotateAlongVector '(0 1 0) 90' > log.rotatePoints

moveBeam -cellZone beam_0 -translate '(0  0.18 0)' > log.moveBeam.beam_0
moveBeam -cellZone beam_1 -translate '(0 -0.18 0)' > log.moveBeam.beam_1

moveBeam -cellZone beam_2 -translate '(0 0.53 0)' > log.moveBeam.beam_2

moveBeam -cellZone beam_3 -translate '(0  0.355 0.3031)' > log.moveBeam.beam_3
moveBeam -cellZone beam_4 -translate '(0  0      0.35 )' > log.moveBeam.beam_4
moveBeam -cellZone beam_5 -translate '(0 -0.355 0.3031)' > log.moveBeam.beam_5

moveBeam -cellZone beam_6 -translate '(0 -0.53 0)' > log.moveBeam.beam_6

moveBeam -cellZone beam_7 -translate '(0 -0.355 -0.3031)' > log.moveBeam.beam_7
moveBeam -cellZone beam_8 -translate '(0  0     -0.35)' > log.moveBeam.beam_8
moveBeam -cellZone beam_9 -translate '(0  0.355 -0.3031)' > log.moveBeam.beam_7


#runApplication $application
