#!/bin/sh

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase
#cleanTimeDirectories

rm -f constant/polyMesh/boundary
rm -r toroidalPulleys
rm -fr VTK
rm -fr history
rm -f *.ps
