#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application name
application=`getApplication`

createMultipleBeamMesh -decomposePatches > log.createMultipleBeamMesh
transformPoints -rotateAlongVector '(0 1 0) 90' > log.rotatePoints

moveBeam -cellZone beam_0 -translate "(-32 15.45 0)" > log.moveBeam.beam-0
#moveBeam -cellZone beam_0 -translate "(-250 16 0)" > log.moveBeam.beam-0

#runApplication $application
