#!/bin/sh
set -x

# Clean library
wclean lib src/wireBunchingModels

# Clean solvers
(cd applications/solvers && wclean all)

# Clean utilities
(cd applications/utilities && wclean all)

# Extra cleaning
\find . -type f \( -name "*~" -o -name "*.bak" \) -exec rm {} \;
\find . \( -name 'core' -o -name 'core.[1-9]*' \) -exec rm {} \;
\find . \( -name '*.pvs' -o -name '*.foam' \) -exec rm {} \;
\find . -name '*.ps' -exec rm {} \;
\rm logs > /dev/null 2>&1
