#!/bin/sh
set -x

# clean library
wclean src/wireBunchingModels

# clean solvers
(cd applications/solvers && wclean all)

# clean utilities
(cd applications/utilities && wclean all)

# Intel MKL library
echo "Checking Intel MKL installation"
if [ -z $MKLROOT ]
then
    echo "Intel MKL library is not installed"
else
    echo "Intel MKL library is instlled."
    wclean src/blockSolvers/BlockMklPardisoSolver
    wclean src/blockSolvers/BlockMklClusterPardisoSolver
fi

# Extra cleaning
\find . -type f \( -name "*~" -o -name "*.bak" \) -exec rm {} \;
\find . \( -name 'core' -o -name 'core.[1-9]*' \) -exec rm {} \;
\find . \( -name '*.pvs' -o -name '*.foam' \) -exec rm {} \;
\find . -name '*.ps' -exec rm {} \;
\rm logs > /dev/null 2>&1

# clean all tutorials
#(cd run && ./Allclean)
