#!/bin/sh
set -x

# Install third-party dependencies
(cd ThirdParty && ./Allwmake)

# Compile library
(cd src/wireBunchingModels && ./Allwmake -j)

# Compile solvers and utilities
wmake applications/solvers/beamFoam

# Compile utilities
wmake -j all applications/utilities

# Install scripts
(cd applications/scripts && ./Allwmake)
