#!/bin/sh
set -x

# Install third-party dependencies
(cd ThirdParty && ./Allwmake)

# Compile library
wmake -j libso src/wireBunchingModels

# Compile solvers and utilities
wmake applications/solvers/beamFoam

# Compile utilities
wmake -j all applications/utilities

# Install scripts
(cd applications/scripts && ./Allwmake)
