#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application name
application=`getApplication`

createMultipleCircularBeamMesh -decomposePatches > log.createMultipleCircularBeamMesh
transformPoints -rotateAlongVector '(0 1 0) 90' > log.rotatePoints

moveBeam -cellZone beam_1 -translate '(0 0.2 0)' > log.moveBeam.translate.beam-1

moveBeam -cellZone beam_2 -rotateAlongVector '(0 0 1) 90' > log.moveBeam.rotate.beam-2
moveBeam -cellZone beam_2 -translate '(0.2 -0.8 0)' > log.moveBeam.translate.beam-2

moveBeam -cellZone beam_3 -rotateAlongVector '(0 0 1) 90' > log.moveBeam.rotate.beam-3
moveBeam -cellZone beam_3 -translate '(0.4 -0.8 0)' > log.moveBeam.translate.beam-3

runApplication $application
