#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application name
application=`getApplication`

#runApplication blockMesh
createMultipleBeamMesh -decomposePatches > log.createMultipleBeamMesh
#createCircularBeamMesh > log.createCircularBeamMesh
transformPoints -rotate-angle '((0 1 0) 90)'



runApplication $application
