#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application name
application=`getApplication`

wmake ./makeCircularArc

#runApplication blockMesh
createCircularBeamMesh > log.createCircularBeamMesh
transformPoints -rotate-angle '(0 1 0) 90' > log.rotatePoints

runApplication makeCircularArc 
runApplication $application
