#!/bin/bash

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Create beam mesh
runApplication createCircularBeamMesh

# Rotate beam to the x direction
runApplication transformPoints -rotate-angle  '((0 1 0) 90)'

# Run the solver
runApplication beamFoam
