#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application name
application=`getApplication`

#runApplication blockMesh
createCircularBeamMesh 
#transformPoints -region beamone -rotate-angle '((0 1 0) 90)' 
transformPoints -rotate-angle '((0 1 0) 90)' 
#setInitialPositionBeam -cellZone beamone -region beamone -translate '(0 0 0)' -rotate '((1 0 0) (0 0 1))'
runApplication $application
