#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application name
application=`getApplication`

runApplication createBeamMesh

runApplication setInitialPositionBeam -cellZone beam_0 -translate '(0 0 0)' -rotateAngle '((0 0 -1) 53.130102)'

runApplication $application
