#!/bin/sh

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

#cleanCase
cleanTimeDirectories

#cleanCase beam-0
#cleanCase beam-1

#foamClearPolyMesh -region beam-0
#foamClearPolyMesh -region beam-1

wclean ./setEndPointTwisting
wclean ./deployWires

#rm -f constant/polyMesh/boundary

rm -f VTK
