#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application name
application=`getApplication`

wmake libso setEndPointTwisting
wmake deployWires

createMultipleCircularBeamMesh > log.createMultipleCircularBeamMesh
transformPoints -rotateAlongVector '(0 1 0) 90' > log.rotatePoints

deployWires > log.deployWires

#runApplication $application
