#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application name
application=`getApplication`

wmake makeBundle

createMultipleCircularBeamMesh > log.createMultipleCircularBeamMesh
transformPoints -rotateAlongVector '(0 1 0) 90' > log.rotatePoints

moveBeam -cellZone beam_1 -translate '(0 0.02 0)' > log.moveBeam.beam_1
moveBeam -cellZone beam_2 -translate '(0 0.01 0.01732051)' > log.moveBeam.beam_2
moveBeam -cellZone beam_3 -translate '(0 -0.01 0.01732051)' > log.moveBeam.beam_3
moveBeam -cellZone beam_4 -translate '(0 -0.02 0)' > log.moveBeam.beam_4
moveBeam -cellZone beam_5 -translate '(0 -0.01 -0.01732051)' > log.moveBeam.beam_5
moveBeam -cellZone beam_6 -translate '(0 0.01 -0.01732051)' > log.moveBeam.beam_6

makeBundle > log.makeBundle

runApplication $application
