#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application name
application=`getApplication`

wmake ./makeArc

#runApplication blockMesh
createCircularBeamMesh > log.createMultipleBeamMesh
transformPoints -rotate-angle '((0 1 0) 90)' 

runApplication makeArc
# runApplication $application
