#!/bin/sh
cd ${0%/*} || exit 1                        # Run from this directory
. $WM_PROJECT_DIR/bin/tools/RunFunctions    # Tutorial run functions

# Mesh, cut out and pretension the two mooring lines (0.orig/beam*,
# constant/beam*, system/beam*)
beamInit/makeBeams || exit 1

# Tank mesh with the floating box cut out
runApplication blockMesh
runApplication topoSet
runApplication subsetMesh -overwrite c0 -patch floatingObject

restore0Dir

# Initial free surface at z = 0.15
runApplication setFields

# Serial run
runApplication $(getApplication)

#------------------------------------------------------------------------------
