#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application name
application=`getApplication`

wmake libso setTransverseDisplacement

runApplication blockMesh
runApplication $application
