#!/bin/sh

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

#cleanCase
cleanTimeDirectories

wclean makeBundle

rm -f constant/polyMesh/boundary
rm -f VTK
rm -rf history*
