#!/bin/sh
cd "${0%/*}" || exit 1                               # Run from this directory

echo "Cleaning beamInitialisation/beam_0"
( cd beamInitialisation/beam_0 && ./Allclean )

echo "Cleaning beamTunnel"
( cd beamTunnel && ./Allclean )

rm -f log.beamInitialisation

#------------------------------------------------------------------------------
