#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application name
application=`getApplication`

createMultipleCircularBeamMesh -decomposePatches > log.createMultipleCircularBeamMesh
transformPoints -rotateAlongVector '(0 1 0) 90' > log.rotatePoints

moveBeam -cellZone beam_0 -translate "(-4000 23 0)" > log.moveBeam.beam-0

#runApplication $application
