#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application name
application=`getApplication`

wmake ./makeHelix

#runApplication blockMesh
createCircularBeamMesh > log.createCircularBeamMesh
transformPoints -rotateAlongVector '(0 1 0) 90' > log.rotatePoints

runApplication makeHelix
runApplication $application
