#!/bin/sh
cd ${0%/*} || exit 1                        # Run from this directory
. $WM_PROJECT_DIR/bin/tools/RunFunctions    # Tutorial run functions


application=$(getApplication)

touch case.foam constant/CofR

# Generate base mesh
runApplication blockMesh

## Removed surfaceFeatureExtract for speed (below)                                                
## Make sure to add it back in when doing actual tests!

runApplication surfaceFeatureExtract

runApplication snappyHexMesh -overwrite

restore0Dir

# Set initial free surface
runApplication setFields



# Run case
# runApplication decomposePar -latestTime -copyUniform -force

#     for beamI in constant/beam*
#     do
#         cp constant/cellDecomposition.beams $beamI/cellDecomposition
#         beamNameI=$(basename $beamI)
#         runApplication -s $beamNameI decomposePar -region $beamNameI -latestTime
#     done



runApplication interFoam

# python3 postProcessing_text.py

# rm -r processor*
