#!/bin/sh

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase
#cleanTimeDirectories

#wclean ./setFirstBeamToCircularArc
#wclean ./setSecondBeam
#wclean ./setBothBeams

#wclean libso setEndPointsDisplacement

rm -f constant/polyMesh/boundary

rm -f VTK
rm -f *.ps
