#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application name
application=`getApplication`

wmake libso setEndPointTwisting

createMultipleBeamMesh -decomposePatches > log.createMultipleBeamMesh
transformPoints -rotateAlongVector '(0 1 0) 90' > log.rotatePoints

moveBeam -cellZone beam_0 -translate "(0 0.02 0)" > log.moveBeam.beam-0
moveBeam -cellZone beam_1 -translate "(0 -0.02 0)" > log.moveBeam.beam-1

runApplication decomposePar

mpirun -np 4 $application -parallel > log.beamFoam

runParallel $application 4
