#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application name
application=`getApplication`

createMultipleCircularBeamMesh -decomposePatches > log.createMultipleCircularBeamMesh
transformPoints -rotateAlongVector '(0 1 0) 90' > log.rotatePoints

moveBeam -cellZone beam_0 -translate "(0 -158.66 0)" > log.moveBeam.beam-0
#moveBeam -cellZone beam_0 -translate "(0 -158.66 30)" > log.moveBeam.beam-0


#moveBeam -cellZone beam_0 -translate "(1650 -158.66 30)" > log.moveBeam.beam-0

#runApplication $application

#vtk2vtp ./conicalPulleys
#rm -rf ./conicalPulleys/*.vtk
