#!/bin/sh
cd ${0%/*} || exit 1                        # Run from this directory
. $WM_PROJECT_DIR/bin/tools/CleanFunctions  # Tutorial clean functions

cleanCase0

# MoorDyn output, restart files and line VTK
rm -rf Mooring/VTK Mooring/*.out Mooring/*.log Mooring/restartFile_* Mooring/lines.txt.ic
rm -f case.foam

#------------------------------------------------------------------------------
