#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

# Get application name
application=`getApplication`

runAnsysToFoam()
{
    if [ -f log.ansysToFoam ]
    then
        echo "ansysToFoam already run on $PWD: remove log file to run"
    else
        echo "ansysToFoam: converting mesh $1"
        ansysToFoam $1 -scale $2 > log.ansysToFoam 2>&1
    fi
}

rm -r 0
cp -r 0.orig 0

runAnsysToFoam flange.ans 0.001

runApplication decomposePar

mpirun -np 4 $(getApplication) -parallel


#------------------------------------------------------------------------------
