#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application name
application=`getApplication`

createMultipleCircularBeamMesh -decomposePatches > log.createMultipleCircularBeamMesh
transformPoints -rotateAlongVector '(0 1 0) 90' > log.rotatePoints

moveBeam -cellZone beam_1 -rotateAlongVector '(0 0 1) 90' > log.moveBeam.rotate.beam-1
moveBeam -cellZone beam_1 -translate '(0.25 -0.25 0.01)' > log.moveBeam.translate.beam-1

runApplication $application
