#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application name
application=`getApplication`

wmake libso ../writeBeamData
wmake ./makeArc

runApplication blockMesh
runApplication makeArc
#runApplication $application
