#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application name
application=`getApplication`

wmake libso setEndPointTwisting

createMultipleBeamMesh > log.createMultipleBeamMesh
transformPoints -rotateAlongVector '(0 1 0) 90' > log.rotatePoints

moveBeam -cellZone beam_0 -translate '(0 0.011547 0)' > log.moveBeam.0
moveBeam -cellZone beam_1 -translate '(0 -0.0057735 -0.01)' > log.moveBeam.1
moveBeam -cellZone beam_2 -translate '(0 -0.0057735 0.01)' > log.moveBeam.2

moveBeam -cellZone beam_3 -translate '(0 -0.0317 0)' > log.moveBeam.3
#moveBeam -cellZone beam_4 -translate '(0  0.0158 -0.0275)' > log.moveBeam.4
#moveBeam -cellZone beam_5 -translate '(0  0.0159 0.0275)' > log.moveBeam.5


#runApplication $application
