#!/bin/sh

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase
#cleanTimeDirectories

wclean ./setFirstBeamToCircularArc
#wclean ./setSecondBeam
#wclean ./setBothBeams

rm -f constant/polyMesh/boundary

rm -f VTK
rm -f *.ps
