#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application name
application=`getApplication`

createMultipleBeamMesh -decomposePatches > log.createMultipleBeamMesh
transformPoints -rotateAlongVector '(0 1 0) 90' > log.rotatePoints

wmake setFirstBeamToCircularArc
#wmake setSecondBeam
#wmake setBothBeams

#moveBeam -cellZone beam_0 -translate "(0 0.01 0)" > log.moveBeam.beam-0
#moveBeam -cellZone beam_1 -translate "(0 -0.01 0)" > log.moveBeam.beam-1


moveBeam -cellZone beam_1 -rotateAlongVector '(0 1 0) 90' -translate "(-1 1.1 1)"> log.moveBeam.beam-1
setFirstBeamToCircularArc > log.setFirstBeamToCircularArc

#setSecondBeam > log.setSecondBeam
#setBothBeams > log.setBothBeams

runApplication $application
